apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: youthconn-demo
build:
  artifacts:
  - image: youthconn-demo
    context: .
    jib:
      project: kr.gracelove:youthconn-demo
      args:
        - "-Dmaven.test.skip=true"
        - "-Djib.to.credHelper=wincred"
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yml
portForward:
  - resourceType: deployment
    resourceName: youthconn-demo
    namespace: default
    port: 8080